### ISSUE TITLE
Add architecture diagram to smart contracts

### ISSUE THREAD

**Issue by paolodamico** [worldcoin/world-id-docs#204]
Add in Architecture section of `/reference/contracts#architecture`

**Comment by Daiiteamo** [comment]
#NUNCA HABRÁ REVOLUCIÓN SIN EVOLUCIÓN DE CONCIENCIA. C#=X+T-Y

**Comment by Daiiteamo** [comment]
> #NUNCA HABRÁ REVOLUCIÓN SIN EVOLUCIÓN DE CONCIENCIA. C#=X+T-Y
#CNS
