### ISSUE TITLE
Question regarding BUILD_ID error

### ISSUE THREAD

**Issue by MorganBergen** [worldcoin/world-id-docs#245]
My attempt to contribute to the docs was halted by the following error, 

<details><summary>after `git clone`</summary>
<code>
❯ brew install pnpm
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
dalfox                             pdfrip                             yatas
==> New Casks
notes-better                                         wave

You have 134 outdated formulae and 2 outdated casks installed.

==> Downloading https://ghcr.io/v2/homebrew/core/pnpm/manifests/8.11.0
################################################################################################## 100.0%
==> Fetching pnpm
==> Downloading https://ghcr.io/v2/homebrew/core/pnpm/blobs/sha256:1bda8356a84ae61c9ce0f1a4d16ade37f58695
################################################################################################## 100.0%
==> Pouring pnpm--8.11.0.arm64_sonoma.bottle.tar.gz
==> Caveats
pnpm requires a Node installation to function. You can install one with:
  brew install node
==> Summary
🍺  /opt/homebrew/Cellar/pnpm/8.11.0: 685 files, 13.3MB
==> Running `brew cleanup pnpm`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
❯ pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +919
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/typescript/4.9.5: 11.62 MB/11.62 MB, done
Downloading registry.npmjs.org/next/13.5.4: 16.80 MB/16.80 MB, done
Progress: resolved 919, reused 0, downloaded 918, added 919, done
Downloading registry.npmjs.org/@next/swc-darwin-arm64/13.5.4: 32.98 MB/32.98 MB, done

dependencies:
+ @docsearch/css 3.5.2
+ @docsearch/react 3.5.2
+ @headlessui/react 1.7.11
+ @mdx-js/loader 2.1.5
+ @mdx-js/react 2.1.5
+ @next/mdx 13.0.3
+ @radix-ui/react-scroll-area 1.0.3
+ @sindresorhus/slugify 2.1.1
+ @tailwindcss/typography 0.5.8
+ @vercel/og 0.5.7
+ @worldcoin/idkit 0.5.1
+ acorn 8.8.1
+ autoprefixer 10.4.7
+ clsx 1.2.1
+ dayjs 1.11.7
+ focus-visible 5.2.0
+ framer-motion 7.8.1
+ mdast-util-to-string 3.1.0
+ mdx-annotations 0.1.1
+ next 13.5.4
+ next-seo 6.0.0
+ next-sitemap 4.0.5
+ postcss-focus-visible 6.0.4
+ postcss-import 15.1.0
+ postcss-nesting 11.2.2
+ postcss-selector-matches 4.0.0
+ posthog-js 1.57.3
+ react 18.2.0
+ react-countup 6.4.2
+ react-dom 18.2.0
+ react-hook-form 7.43.9
+ recma-nextjs-static-props 1.0.0
+ rehype-mdx-title 2.0.0
+ remark-gfm 3.0.1
+ shiki 0.13.0
+ swr 2.1.3
+ tailwindcss 3.3.1
+ unist-util-visit 4.1.1
+ zustand 4.3.2

devDependencies:
+ @types/node 18.15.3
+ @types/react 18.0.28
+ @types/react-dom 18.0.11
+ cspell 6.29.3
+ eslint 8.26.0
+ eslint-config-next 13.0.2
+ prettier 2.7.1
+ prettier-plugin-sort-imports-desc 1.0.0
+ prettier-plugin-tailwindcss 0.1.13
+ ts-node 10.9.1
+ typescript 4.9.5

The dependency was already listed in devDependencies.
If you want to make it a prod dependency, then move it manually.

Done in 9.5s
</code>
</details>

```
❯ pnpm start

> world-id-docs@0.1.0 start /Users/owner/Documents/GitHub/world-id-docs
> next start

[Error: ENOENT: no such file or directory, open '/Users/owner/Documents/GitHub/world-id-docs/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/owner/Documents/GitHub/world-id-docs/.next/BUILD_ID'
}
 ELIFECYCLE  Command failed with exit code 1.
❯ l
```

Do I simply need to `touch BUILD_ID` within the .next directory prior to calling pnpm start?

**Comment by 0xPenryn** [comment]
Hi Morgan! For development work, typically you'd run `pnpm dev` to serve the site locally in a development mode.

If you'd like to run the site in production mode, run `pnpm build` before running `pnpm start`.

Looking forward to your contributions!

**Comment by MorganBergen** [comment]
Thank you!  I don't think I'll have time to play around, and truly make a contribution PR for this.

I'm finishing my degree in C.S. and fortunately/unfortunately I want to continue my education into a M.S. in math.  

--They-- (as in my professors) don't want to take the time out of their day to teach on how to focus on these developmental normalities for important open source projects like this.

Thank you for the tip and I love your work!
